name: Pure Rust project build on Linux
on:
  push:
    branches:
      - main
  pull_request:

env:
  DEBUG: 'napi:*'
  MACOSX_DEPLOYMENT_TARGET: '10.13'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        targets:
          [
            'x86_64-pc-windows-msvc',
            'i686-pc-windows-msvc',
            'aarch64-pc-windows-msvc',
            'x86_64-unknown-linux-gnu',
          ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.targets }}
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'
      - name: Install ziglang
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.11.0
      - run: sudo apt update && sudo apt install -y cups libcups2-dev libcups2
      - run: cargo install cargo-xwin
      - run: yarn install
      - run: yarn build --target ${{ matrix.targets }}
      - uses: actions/upload-artifact@v4
        with:
          name: bindings-${{ matrix.targets }}
          path: ./*.node
          if-no-files-found: error